apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exam-board-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- if .Values.argocd.enabled }}
    argocd.argoproj.io/sync-wave: "6"
    {{- end }}
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingressClassName }}
  rules:
    - http:
        paths:
          {{- range .Values.paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ .service }}
                port:
                  number: {{ .port }}
          {{- end }}
