apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: admin-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: admin=shahiddevops1/exam-result-system-admin_service
    argocd-image-updater.argoproj.io/admin.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: default
  source:
    repoURL: https://github.com/muhammadshahid3/argocd-exam-board-kind
    targetRevision: main
    path: admin-service
  destination:
    server: https://kubernetes.default.svc
    namespace: exam-board
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
