apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exam-board-ingress
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/<your-org>/<your-repo>.git
    targetRevision: main
    path: charts/ingress
  destination:
    server: https://kubernetes.default.svc
    namespace: exam-board
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
