apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/muhammadshahid3/argocd-exam-board-kind
    targetRevision: main
    path: postgres
    # helm:
    #   values: |
    #     auth:
    #       password: super-secret-prod-password
  destination:
    server: https://kubernetes.default.svc
    namespace: exam-board
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
