apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: student-service
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd-image-updater.argoproj.io/image-list: student=shahiddevops1/exam-result-system-student_service
    argocd-image-updater.argoproj.io/student.update-strategy: latest
spec:
  project: default
  source:
    repoURL: https://github.com/muhammadshahid3/argocd-exam-board-kind
    targetRevision: main
    path: student-service/helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: exam-board
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
