apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    {{- include "admin-service.syncWave" (dict "root" $ "wave" "4") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.name }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: {{ .Values.port }}
      protocol: TCP
